/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.12.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth from "../auth.js";
import type * as coupons from "../coupons.js";
import type * as cronHandler from "../cronHandler.js";
import type * as crons from "../crons.js";
import type * as emailHelpers from "../emailHelpers.js";
import type * as emails from "../emails.js";
import type * as encryption from "../encryption.js";
import type * as fileStorage from "../fileStorage.js";
import type * as files from "../files.js";
import type * as http from "../http.js";
import type * as recipients from "../recipients.js";
import type * as stripeActions from "../stripeActions.js";
import type * as subscriptions from "../subscriptions.js";
import type * as timer from "../timer.js";
import type * as totp from "../totp.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  coupons: typeof coupons;
  cronHandler: typeof cronHandler;
  crons: typeof crons;
  emailHelpers: typeof emailHelpers;
  emails: typeof emails;
  encryption: typeof encryption;
  fileStorage: typeof fileStorage;
  files: typeof files;
  http: typeof http;
  recipients: typeof recipients;
  stripeActions: typeof stripeActions;
  subscriptions: typeof subscriptions;
  timer: typeof timer;
  totp: typeof totp;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
